version: "3.4"

services:
  nn01:
    image: hadoop_base:latest
    container_name: nn01
    hostname: nn01
    entrypoint: /entrypoint.sh namenode
    ports:
      - 50070:50070
      - 8088:8088
    networks:
      - bridge

  nn02:
    image: hadoop_base:latest
    container_name: nn02
    hostname: nn02
    entrypoint: /entrypoint.sh secondarynamenode
    ports:
      - 50080:50070
      - 8089:8088
    networks:
      - bridge

  dn01:
    image: hadoop_base:latest
    container_name: dn01
    hostname: dn01
    entrypoint: /entrypoint.sh zkdatanode
    networks:
      - bridge

  dn02:
    image: hadoop_base:latest
    container_name: dn02
    hostname: dn02
    entrypoint: /entrypoint.sh datanode
    networks:
      - bridge

  dn03:
    image: hadoop_base:latest
    container_name: dn03
    hostname: dn03
    entrypoint: /entrypoint.sh datanode
    networks:
      - bridge

networks:
  bridge:
